# Generated by Django 2.2.5 on 2019-10-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurements',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('mtype', models.TextField(blank=True, null=True)),
                ('distance', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('gaiadistance', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sptype', models.TextField(blank=True, null=True)),
                ('propermotion', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('vmag', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('bminusv', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Measurements',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('oid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('ra', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('dec', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('champion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Object',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('obid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('followup', models.BooleanField(blank=True, null=True)),
                ('candidates', models.IntegerField(blank=True, null=True)),
                ('reductionnotes', models.TextField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Observations',
                'managed': False,
            },
        ),
    ]
